---
apiVersion: v1
kind: Service
metadata:
  annotations:
  {{- range $key, $val := .Values.tags }}
    {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- range $key, $val := .Values.web.service.annotations }}
    {{ $key }}: {{ $val | quote }}
  {{- end }}
  name: {{ .Values.web.name }}
  labels:
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service }}
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ports:
  - port: {{ .Values.web.service.port }}
    protocol: TCP
    targetPort: {{ .Values.web.deployment.port }}
    name: http
  selector:
    app: {{ .Values.web.name }}
  type: {{ .Values.web.service.type }}
