---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  {{- range $key, $val := .Values.tags }}
    {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- range $key, $val := .Values.worker.deployment.annotations }}
    {{ $key }}: {{ $val | quote }}
  {{- end }}
  name: {{ .Values.worker.name }}
  labels:
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name | quote }}
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  replicas: {{ .Values.worker.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.worker.name }}
  strategy:
    type: {{ .Values.worker.deployment.updateStrategy.type }}
    {{- if eq .Values.worker.deployment.updateStrategy.type "RollingUpdate" }}
    rollingUpdate:
      maxSurge: {{ .Values.worker.deployment.updateStrategy.maxSurge}}
      maxUnavailable: {{ .Values.worker.deployment.updateStrategy.maxUnavailable}}
    {{- end }}
  template:
    metadata:
      labels:
        app: {{ .Values.worker.name }}
        release: {{ .Release.Name | quote }}
      annotations:
      {{- range $key, $val := .Values.tags }}
        {{ $key }}: {{ $val | quote }}
      {{- end }}
      {{- range $key, $value := .Values.worker.deployment.annotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
    spec:
      {{- if .Values.podSecurityContext }}
      securityContext:
{{ toYaml .Values.podSecurityContext | indent 10 }}
      {{- end }}
      {{- with .Values.worker.deployment.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.worker.deployment.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.worker.deployment.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      containers:
      - image: {{ .Values.worker.image }}:{{ .Values.codecovVersion }}
      {{- with .Values.extraEnvs }}
        env:
{{ toYaml . | nindent 10 }}
      {{- end }}
      {{- if .Values.envFrom }}
        envFrom:
{{ toYaml .Values.envFrom | indent 10 }}
      {{- end }}
        args:
        {{- range $val := .Values.worker.deployment.args }}
          - {{ $val | quote }}
        {{- end }}
        imagePullPolicy: "{{ .Values.imagePullPolicy }}"
        name: {{ .Values.worker.name }}
        resources:
{{ toYaml .Values.worker.deployment.resources | indent 10 }}
        volumeMounts:
        {{- range .Values.secretMounts }}
        - name: {{ .name }}
          mountPath: {{ .path }}
          {{- if .subPath }}
          subPath: {{ .subPath }}
          {{- end }}
        {{- end }}
        - mountPath: /config
          name: codecov-yml
          readOnly: true
      volumes:
      {{- range .Values.secretMounts }}
      - name: {{ .name }}
        secret:
          secretName: {{ .secretName }}
      {{- end }}
      - name: codecov-yml
        configMap:
          name: {{ .Values.configmap.name }}
          defaultMode: 420
    {{- if .Values.extraVolumes }}
{{ toYaml .Values.extraVolumes | indent 8 }}
    {{- end }}
  {{- if .Values.extraVolumes }}
{{ toYaml .Values.extraVolumeMounts | indent 10 }}
  {{- end }}
